apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-in-namespace-swag
  namespace: kyverno
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selector: all()
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
  egress:
  - action: Allow
