apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This sets the destination namespace and project
# These are *validated* using a validating admission webhook.
patches:
# All apps scoped to a specific namespace/project
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: not-used
    spec:
      destination:
        server: https://kubernetes.default.svc
      project: networking
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  target:
    kind: Application

resources:
- application.yaml
- allow-in-namespace.yaml
- csi-driver.yaml
- apiserver-egress.yaml
