apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
#- target:
#    kind: ValidatingWebhookConfiguration
#    name: cert-manager-trust
#  patch: |-
#    - op: add
#      path: /webhooks/0/namespaceSelector/matchExpressions/-
#      value:
#        key: control-plane
#        operator: DoesNotExist

- target:
    kind: Deployment
    name: cert-manager-trust
  patch: |-
    kind: Deployment
    metadata:
      name: ignored
    spec:
      template:
        metadata:
          labels:
            apiserver/ingress: enabled
            apiserver/egress: enabled


resources:
- cert-manager-trust.yaml
