apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: networking
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - https://github.com/dreznicek/argo-namespace-test
  - https://charts.jetstack.io
  # - https://kyverno.github.io/kyverno
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to namespaces project
    policies:
    - p, proj:networking:read-only, applications, get, networking/*, allow
    groups:
    - networking
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: networking-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
  - git:
      repoURL: https://github.com/dreznicek/argo-namespace-test
      revision: HEAD
      directories:
      - path: "networking/*"
        exclude: true
  template:
    metadata:
      name: 'networking-{{path.basename}}'
    spec:
      project: networking
      source:
        repoURL: https://github.com/dreznicek/argo-namespace-test
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
      # ignoreDifferences:
      # - group: admissionregistration.k8s.io
      #   kind: MutatingWebhookConfiguration
      #   jqPathExpressions:
      #     - '.webhooks[]?.clientConfig.caBundle'
      # - group: admissionregistration.k8s.io
      #   kind: ValidatingWebhookConfiguration
      #   jqPathExpressions:
      #     - '.webhooks[]?.clientConfig.caBundle'
