apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml
namePrefix: dev-

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/http/paths/0/path
      value: /dev/test-app
  target:
    kind: Ingress
    name: test-app-ingress

namespace: test-app-dev