apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: networking
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks/0/namespaceSelector
  destination:
    namespace: cert-manager
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.9.1
    helm:
      values: |
        labels: &labels
          apiserver/ingress: enabled
          apiserver/egress: enabled

        podLabels: *labels
        webhook:
          podLabels: *labels
        cainjector:
          podLabels: *labels
        startupapicheck:
          podLabels: *labels

        installCRDs: true

        #extraArgs:
        #- --controllers=*,-certificaterequests-approver
