apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-csi-driver
  namespace: argocd
spec:
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks/0/namespaceSelector
  destination:
    namespace: cert-manager
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager-csi-driver
    targetRevision: v0.4.2
